[tool.poetry]
name = "ape-safe"
version = "0.7.1"
description = "Build complex Gnosis Safe transactions and safely preview them in a forked environment."
authors = ["banteg"]
license = "MIT"
repository = "https://github.com/banteg/ape-safe"
readme = "readme.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
eth-brownie = "^1.19.2"
safe-eth-py = "^5.0.0"
trezor = "^0.13.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
